links:
  rails_tutorial:
    help_page: http://www.railstutorial.org/help
    book_page: https://www.railstutorial.org/book
    home_page: http://www.railstutorial.org/

validations:
  name:
    max_length: 50
  email:
    max_length: 255
    regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i'
  password:
    min_length: 6

remember_me: 1
